version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_local
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: my_event_db
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db

  my-event-api:
    build: .
    container_name: my_event_api
    environment:
      - MONGODB_URL=mongodb://rootuser:rootpass@mongodb:27017/my_event_db?authSource=admin
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
